### PR TITLE
Updated for the latest version of alpheios-core

### PR DESCRIPTION
**Pull request by kirlat**
Refreshed to match `alpheios-core`

### CODE REVIEW

**Comment by kirlat** [comment]
> I don't actually see any code changes here. Should I?

I think it does not require any changes but let me double check that.

**Comment by balmas** [comment]
when I built it the extension didn't load. I didn't debug further but it through an error in content.js somewhere.

**Comment by kirlat** [comment]
> when I built it the extension didn't load. I didn't debug further but it through an error in content.js somewhere.

Let me run a series of tests to make sure it's fully working.

**Comment by kirlat** [comment]
@balmas: I still think webextension package is OK and does not require any changes. It work for me without a hitch. I've just updated the dependencies.

**Comment by balmas** [comment]
ok, you are probably right. I think I missed a step in the build earlier anyway.  Feel free to merge this . I am going to try a new qa build shortly.

**Comment by kirlat** [comment]
Please let me know if you'll discover any problems with it.

**Pull request merged**
