### PR TITLE
Add safari app step 3

### PR DESCRIPTION
**Pull request by irina060981**
I have made the third step - refactor to reduce duplicate code
Also I have renamed it more correctly, changed reference from me to Alpheios in project and targets properties (where I was able to find, may be there are some other places - if I find I will correct too).
Rebuild and rearchived, changed the description and version that is shown in Safari Extensions Tab.

### CODE REVIEW

**Comment by balmas** [comment]
I have mixed feelings about it.  We do include the final distribution javascript for the webextension and it makes it quite easy for distributing test builds. But it does add to the size of the repo.

I guess GitHub recommends including binaries as parts of releases, which can be created via use of the GitHub API (https://help.github.com/articles/creating-releases/) 

Let's make sure it works and get testing going and then decide what to do about this.

**Comment by balmas** [comment]
@irina060981 I am not sure if I am doing something wrong, but I was unable to do anything with the dmg file by itself. I can install it, but it just gives me the AlpheiosSafariApp which it says is signed by an unknown developer.

**Comment by irina060981** [comment]
@balmas, if I correctly understood this article from Apple - 
https://support.apple.com/kb/PH25088?locale=en_US

These warning is a part of a security check workflow.
I have signed the extension with simple MacOS Developer Certificate (and Safari App Extension certificate), but for the purpose this application become safe for distribution - it should be signed with Developer ID Certificate. But I don't have permission for creating such certificate (as XCode said me).

You could anyway open such an application (according to Apple's article), for this purpose you could add it to security exception.
Or I believe (but I am not sure) - You could sign this build with Developer ID certificate as an administrator of Alpheios Apple Team.

**Comment by irina060981** [comment]
I will merge the branch for not preventing @kirlat to add new changes (iframe issue) as it is approved, hope noone will be against.

**Pull request merged**
