### PR TITLE
Move options to data models

### PR DESCRIPTION
**Pull request by irina060981**
It is update for this PR https://github.com/alpheios-project/alpheios-core/pull/551
It is really tiny - only changed references.

For now I couldn't build it properly because of https://github.com/alpheios-project/alpheios-core/issues/549
And check, but I checked my changes with embeded-lib.
I talked to @kirlat  about the issue and I think I could merge this really tiny change - while Kirill is working with his issue.

### CODE REVIEW

**Review by kirlat — APPROVED** [review]
Looks good!

**Review by balmas — CHANGES_REQUESTED** [review]
I think Options should be exposed from components in the same way as Logger

https://github.com/alpheios-project/alpheios-core/pull/551#pullrequestreview-525126672

**Comment by kirlat** [comment]
> I think Options should be exposed from components in the same way as Logger

Second that

**Comment by irina060981** [comment]
I wrote my opinioin inside other PRs. But anyway let's do it as you suggest.

**Pull request closed without merging**
